### PR TITLE
Enable mingw and macos build

### PR DESCRIPTION
**Pull request by maelvls**
Hello,

I had to hack your excellent project to adapt it for win32+mingw and macos builds. In this PR, I propose
* an update of quantor and picosat (solves most problems with windows and macos)
* added a test for quantor
* tests are now built and run from `make test` (I used oUnit2 to ease the testing)
* build and run only the tests that correspond to the libraries enabled (quantor or depqbf)
* fix the `ld: -L` warning
* ~~fix the ocamlbuild tags warnings~~ my fix breaks the build for older versions of ocaml
* add travis and appveyor (macos, linux and windows)
* In quantor's configure script, mingw's gcc can't be recognized because it does not match `*gcc` or `gcc*`. I simply modified to `*gcc*` so that `x86_64-w64-mingw32-gcc.exe` works.
* I couldn't build quantor-3.2 work with mingw64-x86_64, it only works on i686. This is a problem of ./configure that does not finds the right 'Word' size (mingw x86_64, `sizeof(long long long) == sizeof(void*)`). I also did a related small fix in ./configure (removed all `\n` from printf to avoid windows CRLF problems)

Like for the ocaml-minisat project where we discussed about simply naming the opam package `minisat`, I also propose to name the opam package `qbf`; but I can still go back to `ocaml-qbf`, no problem!

I also bumped to version 0.2 (I can discard that; as you wish)

### CODE REVIEW

**Comment by c-cube** [comment]
This is very impressive. Thanks for the hard work. I have to test the changes, obviously, but this looks very nice. You must obviously add yourself to the list of maintainers and/or authors ;-)

**Comment by maelvls** [comment]
Thanks! This is rewarding to have such nice feedback on PRs :blush:

By the way, I also propose to add travis (linux, mac) and appveyor (if you wish!).

Note: I am still working on some commits (like the `-fPIC` one); I'll keep you updated

**Comment by c-cube** [comment]
I'll be informed by github notifications ;-)
Well it's nice to see such contributions! CI is a good thing to have (I think I have to authorize the repository at some point, we'll see after this gets merged).

**Comment by maelvls** [comment]
I think I am done! It works on macos, linux and native windows (mingw 32 bits).

capture d ecran 2017-06-02 a 13 16 12

Travis and appveyor also run the tests at the end:

* [![Travis][1]][2] (Linux and MacOS builds) 
* [![Appveyor][3]][4] (Windows)

[1]: https://travis-ci.org/maelvalais/ocaml-qbf.svg?branch=master
[2]: https://travis-ci.org/maelvalais/ocaml-qbf
[3]: https://ci.appveyor.com/api/projects/status/d5cjdyqalnlaqxb5?svg=true
[4]: https://ci.appveyor.com/project/maelvalais/ocaml-qbf

**Comment by maelvls** [comment]
Excellent! 👍 

Now, what do you think about distributing it though opam? I can open a PR on [opam-repository][1] if you want (their continuous integration tests may fail on ocaml-qbf, I guess some work will still be required to pass them on all architectures)

You can also try to enable travis-ci and appveyor (but this is way less important 😃).

[1]: https://github.com/ocaml/opam-repository/pulls

**Comment by c-cube** [comment]
Oh, it's not on opam yet? my bad.
I'm going to look at how to enable travis and appveyor, too.

Thanks for your work :-)

**Comment by c-cube** [comment]
Feel free to do the opam query (e.g. with opam-publish)!

**Comment by maelvls** [comment]
Ok! Just submitted the [PR](https://github.com/ocaml/opam-repository/pull/9452). I just had to fix the opam's descr before and create the tag 0.2

**Comment by maelvls** [comment]
Oh! I just noticed that the `Source repo:` might be wrong:

    Source repo: https://github.com/c-cube/quantor.git

**Comment by c-cube** [comment]
You can modify stuff and re-run opam-publish :-)

**Comment by maelvls** [comment]
Done! Now the dev-repo is ok!
Thanks!

**Comment by maelvls** [comment]
The package `qbf` is now on [opam]! Excellent!
Thanks again,

Maël 

[opam]: https://opam.ocaml.org/packages/qbf/

**Comment by c-cube** [comment]
Thanks to you!

**Pull request merged**
