### PR TITLE
opam: convert from 1.2 to 2.0 format

### PR DESCRIPTION
**Pull request by maelvls**
Note that findlib isn't relevant anymore. As an example, oasis2opam
is not generating this file anymore: https://github.com/ocaml/opam/issues/2948

@c-cube Do you think we should convert?

### CODE REVIEW

**Comment by c-cube** [comment]
Convert what? The opam file seems fine, but I think moving to dune will also be useful before making a new release.

**Comment by maelvls** [comment]
Hmm... I now realize that this PR doesn't make any sense, what is the rationale behind moving to the 2.0 format?

The actual reason why I opened the PR was rather to fix the issue I found when trying the `opam publish` command; it gives me the following:

```sh
> opam publish

[WARNING] Opam file /Users/mvalais/code/ocaml-qbf/opam/opam has 1.2 format,
          which is not accepted on 2.0 repository.
 Update it inplace to 2.0 format? [Y/n] y

The following will be published:
  - qbf version 0.3 with opam file at /Users/mvalais/code/ocaml-qbf/opam/opam
  - qbf version 0.3 with opam file at /Users/mvalais/code/ocaml-qbf/opam/opam

[ERROR] Multiple publications with the same name are not allowed
```

There might be a bug with `opam publish` (or I misinterpreted how to use it); as a workaround, I did

```sh
> mv opam/opam opam/qbf.opam
> opam publish
[WARNING] Opam file /Users/mvalais/code/ocaml-qbf/opam/qbf.opam has 1.2 format,
          which is not accepted on 2.0 repository.
 Update it inplace to 2.0 format? [Y/n] y

The following will be published:
  - qbf version 0.3 with opam file at
    /Users/mvalais/code/ocaml-qbf/opam/qbf.opam

[WARNING] These will be virtual packages: qbf.0.3

Continue ? You will be shown the patch before submitting. [Y/n]
```
or 
```sh
> mv opam/ qbf.opam/
> opam publish
[WARNING] Opam file /Users/mvalais/code/ocaml-qbf/qbf.opam/opam has 1.2 format,
          which is not accepted on 2.0 repository.
 Update it inplace to 2.0 format? [Y/n] y

The following will be published:
  - qbf version opam with opam file at
    /Users/mvalais/code/ocaml-qbf/qbf.opam/opam

[WARNING] These will be virtual packages: qbf.opam

Continue ? You will be shown the patch before submitting. [Y/n]
```

Anyway, sorry for the inconvenience! We can still open a PR to https://github.com/ocaml/opam-repository directly without `opam publish` 🙂

**Comment by maelvls** [comment]
Btw, could I create a new tag `0.3` with the current master? So that it can be built with opam 2 🙂

**Comment by c-cube** [comment]
The rationale for moving to opam2 is that opam 1 is no longer supported, and that the repository uses version 2.0. But I can migrate it myself, no worries. Moving to dune would be more helpful I think.

**Comment by c-cube** [comment]
btw I think you didn't push the tag, I don't see it on github :)

**Pull request closed without merging**
