### PR TITLE
Move to Github Actions

### PR DESCRIPTION
**Pull request by maelvls**
At first, I just wanted to update and fix the `.travis-ci.yml` and `appveyor.yml`. And since I had already made the change to Github Actions on [touist](https://github.com/touist/touist) and [ocamlyices2](https://github.com/maelvls/ocamlyices2), I figured why not move ocaml-qbf to it too?

### CODE REVIEW

**Comment by c-cube** [comment]
wait until #7 is merged, it disables these terrible warnings

**Comment by c-cube** [comment]
I'm tired of this, will resume later unless you want to try and make it work

**Comment by maelvls** [comment]
I’ll try now 😅 Fixing CI is such a time sink

**Comment by maelvls** [comment]
Finallyyy 🎉🎉🎉

**Comment by maelvls** [comment]
Finallyyy it passes!! 🎉🎉

Edit: almost

**Comment by maelvls** [comment]
Yes! Now it works 😁

**Comment by c-cube** [comment]
Awesome, thank you!

**Pull request merged**
